config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "home/search"

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "pay", to: "payments#create", as: "pay"

  resources :cart, only: [:index, :destroy]

  resources :products, only: [:index, :show] do
    member do
      resource :cart, only: :update do
        [:add, :remove, :update_amount].each do |action|
          post action, to: "cart#update", as: "#{action}_product_in", defaults: { action_type: action }
        end
      end
    end
  end

  get :about, to: "home#about"

  get :thanks_for_payment, to: "home#thanks_for_payment"

  resources :orders
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_cart, :cart_params_valid?, only: :update

  def index
    @cart = Cart::StorageService.new(session, params)
  end

  def update
    service = Cart::ManagerService.new(session, cart_params)

    service.call

    redirect_back fallback_location: root_path, notice: (I18n.t "cart.notice.#{params[:action_type]}")
  end

  def destroy
    session.delete(:products)

    redirect_to products_path, notice: "Cart was cleaned"
  end

  private

  def cart_params
    params.permit(:id, :amount, :action_type)
  end

  def initialize_cart
    session[:products] = {} unless session[:products].present?
  end

  def cart_params_valid?
    return if cart_params[:id].present?

    redirect_back fallback_location: root_path, alert: "Something went wrong"
  end
end

app/views/cart/_buy_form.html.erb
<%= form_with url: add_product_in_cart_path(product) do |f| %>
  <%= f.number_field :amount, class: "input-field w-24 h-9 inline-block", min: 2, placeholder: "1" %>
  <%= f.submit "Add to cart", class: "btn-black" %>
<% end %>

app/views/cart/_change_amount_form.html.erb
<%= form_with url: update_amount_product_in_cart_path(product) do |f| %>
  <%= f.number_field :amount, class: "input-field w-24 h-9 inline-block", value: @cart.product_amount(product), min: 1 %>
  <%= f.submit "Change amount", class: "btn-black" %>
<% end %>

app/views/cart/index.html.erb
<div class="container flex flex-col mx-auto">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <% if @cart.products_count.nonzero? %>
          <table class="min-w-full text-sm font-light text-left">
            <thead class="font-medium border-b dark:border-neutral-500">
              <tr>
                <th scope="col" class="px-6 py-4">Title</th>
                <th scope="col" class="px-6 py-4">Price</th>
                <th scope="col" class="px-6 py-4">Amount</th>
                <th scope="col" class="px-6 py-4">Sum</th>
              </tr>
            </thead>
              <tbody>
                <% @cart.realized_products.each do |product| %>
                  <tr class="transition duration-300 ease-in-out border-b hover:bg-neutral-100 dark:border-neutral-500 dark:hover:bg-neutral-600">
                    <td class="table-item"><%= product.name %></td>
                    <td class="table-item"><%= number_to_currency(product.price, unit: "₴ ") %></td>
                    <td class="table-item">
                      <%= render "cart/change_amount_form", product: product %>
                    </td>
                    <td class="table-item"><%= number_to_currency(@cart.product_sum(product), unit: "₴ ") %></td>
                    <td class="table-item">
                      <%= button_to remove_product_in_cart_path(product) do %>
                          <i class="fa fa-regular fa-trash fa-2x"></i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
                <tr class="border-b dark:border-neutral-500">
                  <td colspan="3" class="px-6 py-2 whitespace-nowrap">
                    Total sum
                  </td>
                  <td class="px-6 py-2 whitespace-nowrap"><%= number_to_currency(@cart.sum, unit: "₴ ") %></td>
                </tr>
              </tbody>
          </table>

          <div>
            <div class="inline-block m-5">
                <%= link_to 'Pay this order', new_order_path, class: "btn-black" %>
            </div>

            <div class="inline-block float-right m-5">
              <%= button_to 'Delete all products', cart_path(@cart), method: :delete, class: "btn-grey ms-0" %>
            </div>
          </div>
        <% else %>
            <div class="grid h-screen text-3xl place-items-center">Your cart is empty yet</div>
        <% end %>
      </div>
    </div>
  </div>
</div>