config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get "home/search"

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "pay", to: "payments#create", as: "pay"

  resources :cart, only: [:index, :destroy]

  resources :products, only: [:index, :show] do
    member do
      resource :cart, only: :update do
        [:add, :remove, :update_amount].each do |action|
          post action, to: "cart#update", as: "#{action}_product_in", defaults: { action_type: action }
        end
      end
    end
  end

  get :about, to: "home#about"

  get :thanks_for_payment, to: "home#thanks_for_payment"

  resources :orders
end

app/models/order.rb
class Order < ApplicationRecord
  scope :ordered, -> { order(created_at: :asc) }

  has_many :product_orders, dependent: :destroy
  has_many :products, through: :product_orders

  belongs_to :customer, class_name: 'User', foreign_key: :customer_id, required: false

  belongs_to :promocode, required: false

  validates :first_name, :last_name, :address, :phone, presence: true

  def product_sum(product)
    product_orders.joins(:product)
                  .where(order_id: id, products: { id: product.id })
                  .sum('product_orders.amount * products.price')
  end

  def product_amount(product)
    product_orders.find_by(product:).amount
  end

  def total_sum
    product_orders.joins(:product)
                  .where(order_id: id)
                  .sum('product_orders.amount * products.price')
  end

  def customer_full_name
    "#{first_name} #{last_name}"
  end

  def discount
    promocode.discount_is_fixed ? "₴ #{promocode.discount}" : "#{promocode.discount}%"
  end

  def final_sum
    if promocode.discount_is_fixed
      sum = total_sum - promocode.discount.to_d
    else
      sum = total_sum * ((100 - promocode.discount.to_f) / 100)
    end

    [sum, 0.01].max
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: :index
  before_action :check_cart, only: :new

  def index
    @orders = current_user.orders
  end

  def show
    @order = resourse
  end

  def new
    @cart = Cart::StorageService.new(session, params)
    @order = Order.new
  end

  def create
    @cart = Cart::StorageService.new(session, params)
    @order = Order.new(order_params)

    if params[:promocode].present?
      promo = Promocode.find_by(code: params[:promocode])
      @order.promocode = promo if promo.present?
    end

    if @order.save
      Orders::ManagerService.new(@order, session).call

      redirect_to order_path(@order), notice: "Order was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def collection
    Order.ordered
  end

  def resourse
    collection.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:first_name, :last_name, :address, :phone, :customer_id)
  end

  def check_cart
    redirect_to root_path, alert: "Your cart is empty yet" if session[:products].blank?
  end
end

app/views/orders/_form.html.erb
<%= simple_form_for order, defaults: { input_html: { class: 'input-field w-2/3' } } do |f| %>
  <%= f.hidden_field :customer_id,  value: current_user&.id %>
  <%= f.input :first_name, input_html: { value: current_user&.first_name } %>
  <%= f.input :last_name, input_html: { value: current_user&.last_name } %>
  <%= f.input :address, input_html: { value: current_user&.address } %>
  <%= f.input :phone, input_html: { value: current_user&.phone } %>

  <p>Promocode</p>
  <%= text_field_tag :promocode, '', class: 'input-field w-full' %><br>

  <%= f.button :submit, class: 'btn-black mb-5 p-5' %>
<% end %>

app/views/orders/index.html.erb
<div class="flex flex-col items-center justify-center mt-5">
  <% if @orders.exists? %>
    <table class="justify-center w-2/3 text-left text-sm font-light shadow-2xl">
      <thead class="border-b font-medium dark:border-neutral-500">
        <tr>
          <th scope="col" class="px-6 py-4">№</th>
          <th scope="col" class="px-6 py-4">Date</th>
          <th scope="col" class="px-6 py-4">Sum</th>
        </tr>
      </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr class="border-b transition duration-300 ease-in-out hover:bg-neutral-100 dark:border-neutral-500 dark:hover:bg-neutral-600">
              <td class="whitespace-nowrap px-6 py-4 font-medium"><%= order.id %></td>
              <td class="whitespace-nowrap px-6 py-4"><%= l order.created_at, format: :long %></td>
              <td class="whitespace-nowrap px-6 py-4"><%= number_to_currency(order.total_sum) %></td>
              <td class="whitespace-nowrap px-6 py-4">
                <%= link_to order_path(order) do %>
                    <i class="fa-solid fa-arrow-up-right-from-square fa-2xl"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
    </table>
  <% else %>
    <div class="grid h-screen place-items-center text-3xl">Your didn't buy anything yet</div>
  <% end %>
</div>

app/views/orders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Create order</h1>

  <%= render "orders/form", order: @order %>

  <p class="text-2xl mt-5">You choose:</p>

  <table class="min-w-full text-left text-sm font-light">
    <thead class="border-b font-medium dark:border-neutral-500">
      <tr>

        <th scope="col" class="px-6 py-4">Title</th>
        <th scope="col" class="px-6 py-4">Price</th>
        <th scope="col" class="px-6 py-4">Amount</th>
        <th scope="col" class="px-6 py-4">Sum</th>
      </tr>
    </thead>
    <tbody>
      <% @cart.realized_products.each do |product| %>
        <tr class="border-b transition duration-300 ease-in-out hover:bg-neutral-100 dark:border-neutral-500 dark:hover:bg-neutral-600">
          <td class="table-item"><%= product.name %></td>
          <td class="table-item"><%= number_to_currency(product.price, unit: "₴ ") %></td>
          <td class="table-item"><%= @cart.product_amount(product) %></td>
          <td class="table-item"><%= number_to_currency(@cart.product_sum(product), unit: "₴ ") %></td>
        </tr>
      <% end %>
      <tr class="border-b dark:border-neutral-500">
        <td colspan="3" class="whitespace-nowrap px-6 py-2">
          Total sum
        </td>
        <td class="whitespace-nowrap px-6 py-2"><%= number_to_currency(@cart.sum, unit: "₴ ") %></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Back to cart',cart_index_path, class: "btn-grey mt-5 mb-5" %>
</div>

app/views/orders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <div class="flex flex-col text-base sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">

        <div class="block shadow-2xl p-6">
          <ul class="ms-6 w-96">
            <h1 class="font-bold text-3xl mb-5">Order №<%= @order.id %></h1>
            <li class="mb-4"><%= @order.customer_full_name %></li>
            <li class="mb-4"><%= @order.address %></li>
            <li class="mb-4"><%= @order.phone %></li>
          </ul>
          <table class="min-w-full text-left text-sm font-light">
            <thead class="border-b font-medium dark:border-neutral-500 text-left">
              <tr>
                <th scope="col" class="pe-6 py-4">Title</th>
                <th scope="col" class="pe-6 py-4">Price</th>
                <th scope="col" class="pe-6 py-4">Amount</th>
                <th scope="col" class="pe-6 py-4">Sum</th>
              </tr>
            </thead>

            <tbody>
              <% @order.products.each do |product| %>
                <tr class="border-b">
                  <td class="cart-item"><%= product.name %></td>
                  <td class="cart-item"><%= number_to_currency(product.price, unit: "₴ ") %></td>
                  <td class="cart-item"><%= @order.product_amount(product) %></td>
                  <td class="cart-item"><%= number_to_currency(@order.product_sum(product), unit: "₴ ") %></td>
                </tr>
              <% end %>

              <tr class="border-b">
                <td colspan="3" class="whitespace-nowrap font-medium pe-11 py-2 text-right">
                  Total sum
                </td>
                <td class="whitespace-nowrap pe-6 py-2"><%= number_to_currency(@order.total_sum, unit: "₴ ") %></td>
              </tr>

              <% if @order.promocode.present? %>
                <tr class="border-b">
                  <td colspan="3" class="whitespace-nowrap font-medium pe-11 py-2 text-right">
                    Discount
                  </td>
                  <td class="whitespace-nowrap pe-6 py-2"><%= @order.discount %></td>
                </tr>

                <tr class="border-b">
                  <td colspan="3" class="whitespace-nowrap font-medium pe-11 py-2 text-right">
                    Final sum
                  </td>
                  <td class="whitespace-nowrap pe-6 py-2"><%= number_to_currency(@order.final_sum, unit: "₴ ") %></td>
                </tr>
              <% end %>
              </tbody>

          </table>
          <%= link_to "PAY", pay_path(amount: @order.total_sum, discount: @order.promocode&.discount, discount_is_fixed: @order.promocode&.discount_is_fixed), class:"btn-black" %>
          <%# pay_path(amount: @order.total_sum, discount: @order.discount, discount_is_fixed: @order.discount_is_fixed) %>
        </div>
      </div>
    </div>
  </div>
</div>